/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<'Home', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    'Buses': RouteRecordInfo<'Buses', '/admin/buses', Record<never, never>, Record<never, never>>,
    'Dashboard': RouteRecordInfo<'Dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'Tickets': RouteRecordInfo<'Tickets', '/admin/tickets', Record<never, never>, Record<never, never>>,
    'Trips': RouteRecordInfo<'Trips', '/admin/trips', Record<never, never>, Record<never, never>>,
    'Users': RouteRecordInfo<'Users', '/admin/users', Record<never, never>, Record<never, never>>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
    'Login': RouteRecordInfo<'Login', '/auth/login', Record<never, never>, Record<never, never>>,
    'Register': RouteRecordInfo<'Register', '/auth/register', Record<never, never>, Record<never, never>>,
  }
}
